---
- name: JDK Repository
  become: yes
  become_method: sudo
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'

- name: Oracle JDK Repository
  become: yes
  become_method: sudo
  apt_repository:
    repo: 'ppa:webupd8team/java'

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: yes
  apt: 
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Add JAVA Home ZSH /usr/lib/jvm/java-8-oracle
  lineinfile: dest="/home/{{ os.user  }}/.zshrc" line="export JAVA_HOME=/usr/lib/jvm/java-{{ languages.java.version  }}-oracle" 
  become: no

- name: Add Java Home path to bin path ZSH
  lineinfile: dest="/home/{{ os.user }}/.zshrc" line="export PATH=$PATH:$JAVA_HOME/bin"
  become: no

- name: Download Gradle
  get_url: url=https://services.gradle.org/distributions/gradle-{{ languages.java.gradle.version }}-bin.zip dest="/home/{{ os.user }}/gradle-{{ languages.java.gradle.version }}-bin.zip" dest="/home/{{ os.user }}/gradle-{{ languages.java.gradle.version }}-bin.zip"
  become: no

- name: Create the directory for Gradle
  file: path=/usr/local/opt state=directory 
  become: yes
  become_method: sudo

- name: Install Unzip
  become: yes
  become_method: sudo
  apt: 
    name: "unzip"
    state: present 
  
- name: Unzip Gradle
  unarchive: src="/home/{{ os.user }}/gradle-{{ languages.java.gradle.version }}-bin.zip" dest="/usr/local/opt/" creates=yes copy=no
  become: yes
  become_method: sudo

- name: Add Gradle Home ZSH
  lineinfile: dest="/home/{{ os.user }}/.zshrc" line="export GRADLE_HOME=/usr/local/opt/gradle-{{ languages.java.gradle.version  }}"
  become: no

- name: Add Gradle Home path to bin path ZSH
  lineinfile: dest="/home/{{ os.user  }}/.zshrc" line="export PATH=$PATH:$GRADLE_HOME/bin" 
  become: no

- name: Add a simple helper method
  lineinfile: 
    dest: "/home/{{ os.user  }}/.zshrc" 
    line: |
      function getDockerKafkaBrokers { 
        docker-compose ps kafka | tail -n +3 | tr -s ' ' | cut -d' ' -f4 | cut -d'-' -f1 | paste -sd ','
      } 
  become: no

# create a directory if it doesn't exist
- name: Create VIM directories
  file:
    path: "/home/{{ os.user }}/.vim/ftplugin/"
    state: directory
    mode: 0755
- name: vimrc for JAVA
  copy: src=java.vim dest="/home/{{ os.user }}/.vim/ftplugin/java.vim" owner="{{ os.user }}" group="{{ os.user }}" mode=0644
